[phases.build]
cmds = [
  "composer install --no-interaction --prefer-dist --optimize-autoloader",
  "php artisan key:generate --force",
  "php artisan migrate --force",
  "php artisan config:cache",
  "php artisan route:cache"
]
